class BridgewatcherError(Exception): ...


class PriceProviderError(BridgewatcherError): ...


class UncraftableItemCraftedError(BridgewatcherError): ...


class InsufficientDataError(BridgewatcherError): ...
