class BridgewatcherError(Exception): ...


class PriceProviderError(BridgewatcherError): ...


class UncraftableItemCraftedError(BridgewatcherError): ...


class InsufficientDataError(BridgewatcherError): ...


class NoItemFoundError(BridgewatcherError): ...


class UntrackedItemRequested(BridgewatcherError): ...
